### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by nyurik** [openmaptiles/postserve#16]
Code from this repo has long moved to https://github.com/openmaptiles/openmaptiles-tools#test-tiles 
please move all tasks, replace README and description with the link, and archive it to avoid confusion. Thanks!

**Comment by klokan** [comment]
Thank you very much Yuri for working on this!

**Comment by klokan** [comment]
README updates, issues closed, this repo is archived.

Let's continue on https://github.com/openmaptiles/openmaptiles-tools
