### ISSUE TITLE
Improve generating of SQL Queries

### ISSUE THREAD

**Issue by ghost** [openmaptiles/postserve#3]
Right now it's really ugly, should be cleaned up

**Comment by MattBlissett** [comment]
In https://github.com/gbif/postserve/blob/3a4b3b440858519724503f2361d678bb25aecb4e/server.py#L31 I have some even more ugly code to account for buffers.

I aim to tidy it up and make a PR.

**Comment by ianthetechie** [comment]
This could be so much better (and marginally faster too) with [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings)

**Comment by nyurik** [comment]
Please note that postserve has been merged into tools - https://github.com/openmaptiles/openmaptiles-tools#test-tiles and this repo should be closed. Thanks!
