### ISSUE TITLE
Could you check in a copy of your /mapping/data.yml?

### ISSUE THREAD

**Issue by gabefair** [openmaptiles/postserve#7]
Hello, Thank you for doing this. I was wondering if you could checkin your `/mapping/data.yml` file.

 I know its pretty easy to deduce, a json with one 'layers' attribute array. But I'm unfamiliar with yml files or how you might have set yours up.

**Comment by ianthetechie** [comment]
Looks like this repo doesn't get much traffic, eh? The file you're looking for is generated by this: https://github.com/openmaptiles/openmaptiles. When you do an openmaptiles "build" you'll end up with an `openmaptiles.tm2source` directory which contains a file named `data.yaml`.

**Comment by nyurik** [comment]
Please note that postserve has been merged into tools - https://github.com/openmaptiles/openmaptiles-tools#test-tiles and this repo should be closed. Thanks!

**Comment by nyurik** [comment]
Please note that postserve has been merged into tools - https://github.com/openmaptiles/openmaptiles-tools#test-tiles and this repo should be closed. Thanks!
